#!/usr/bin/env python3
"""Emit N functions of EmitC-shaped C++, so the host compiler can be timed on them.

    ctcompile/utils/s0-emit.py --functions 4000 --per-tu 250 --ops 40 --out /tmp/s0

THE COMPILE-TIME RISK IS THE ONE EmitC CARRIES AND THE LLVM BACKEND DOES NOT.
Babylon is 31,905 function_protos in ONE program - every corpus here is a single
UMD bundle, so there is no per-module split and Phase 10C has to partition over
functions. If the host compiler takes even 10 ms per function, that is five
minutes of build for one library.

This emits code shaped like what a backend would produce rather than something
convenient to generate: registers are `value` locals, the numeric fast path is
open-coded against the NaN-boxed representation, and the slow path is a call the
optimiser must not be able to see through. It includes the REAL runtime header,
because per-translation-unit header cost is most of what a partition trades away.
"""
import argparse
import pathlib
import random

PROLOGUE = """// GENERATED by ctcompile/utils/s0-emit.py - not part of the build.
#include <ctbrowser/script/value.hpp>

#include <cstdint>

using ctbrowser::script::value;

// Stands in for the slow path a real backend would call: opaque to the
// optimiser, so the fast-path branch below cannot be folded away. A real
// generated function calls ct_aot_* helpers here, which on the EmitC backend
// are inline C++ the host compiler CAN see through - that difference is the
// throughput half of S0, not the compile-time half this file measures.
// EXTERNAL, not internal: an undefined function in an anonymous namespace is a
// warning in its own right, and this file measures compile time rather than
// linking. External also matches what a real backend emits - the helper lives
// in the runtime, not in the generated translation unit.
value slow_binary(value a, value b) noexcept;
"""

FUNCTION_HEAD = """
namespace {

// One compiled JavaScript function: registers are locals, the numeric fast path
// is open-coded, and anything else is a call.
value ct_fn_%d(value a0, value a1) noexcept {
    value r[%d];
    r[0] = a0;
    r[1] = a1;
"""

# Shapes a real body is made of, in the proportions a bundle actually has:
# arithmetic on registers, a compare-and-branch, and a call that escapes.
OPS = [
    "    r[{d}] = (r[{x}].is_number() && r[{y}].is_number())\n"
    "                 ? value::number(r[{x}].as_number() + r[{y}].as_number())\n"
    "                 : slow_binary(r[{x}], r[{y}]);",
    "    r[{d}] = (r[{x}].is_number() && r[{y}].is_number())\n"
    "                 ? value::number(r[{x}].as_number() * r[{y}].as_number())\n"
    "                 : slow_binary(r[{x}], r[{y}]);",
    "    if (r[{x}].is_number() && r[{x}].as_number() > {k}.0) {{ r[{d}] = r[{y}]; }}",
    "    r[{d}] = slow_binary(r[{x}], r[{y}]);",
    "    r[{d}] = value::number(static_cast<double>({k}));",
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--functions", type=int, default=4000)
    ap.add_argument("--per-tu", type=int, default=250)
    ap.add_argument("--ops", type=int, default=40, help="operations per function")
    ap.add_argument("--regs", type=int, default=16)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    rng = random.Random(1)          # deterministic: the same corpus every run
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    for stale in out.glob("s0_*.cpp"):
        stale.unlink()

    tus, fn = 0, 0
    while fn < args.functions:
        body = [PROLOGUE]
        for _ in range(min(args.per_tu, args.functions - fn)):
            body.append(FUNCTION_HEAD % (fn, args.regs))
            for _ in range(args.ops):
                shape = rng.choice(OPS)
                body.append(shape.format(d=rng.randrange(args.regs), x=rng.randrange(args.regs),
                                         y=rng.randrange(args.regs), k=rng.randrange(100)))
            body.append("    return r[0];\n}\n\n} // namespace\n")
            fn += 1
        (out / f"s0_{tus:04d}.cpp").write_text("\n".join(body))
        tus += 1

    print(f"{fn} functions in {tus} translation units, {args.ops} ops each -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
