// ctjs-opt - the CTJS optimizer driver.
//
// BUILT BEFORE A SINGLE OPERATION EXISTS, which the policy asks for in as many
// words: "Build ctjs-opt in Phase 7, before defining a single operation. It is
// a thin MlirOptMain wrapper and it makes every subsequent phase testable." A
// dialect defined before its test driver cannot be validated, and the first
// fifty operations would then be written without feedback.
#include <ctcompile/Support/MLIRContextSetup.hpp>

#include "ctcompile/CTJS/Transforms/Passes.h"

#include "ctcompile/CTNative/Transforms/Passes.h"
#include "mlir/Conversion/Passes.h"
#include "mlir/IR/DialectRegistry.h"
#include "mlir/Tools/mlir-opt/MlirOptMain.h"

int main(int argc, char ** argv) {
    mlir::DialectRegistry registry;
    ctcompile::registerCTCompileDialects(registry);
    // Generated by -gen-pass-decls, which is what makes --ctjs-lower-to-runtime
    // a flag without a line of registration written by hand.
    ctcompile::ctjs::registerCTJSPasses();
    // And the native tier's, Phase 62½ - the same generated registration.
    ctcompile::ctnative::registerCTNativePasses();
    // AND THE TWO UPSTREAM CONVERSIONS THIS PROJECT NEEDS, which this tool did
    // not register at all. They recover structured control flow from a CFG
    // built out of jumps, and neither is ours to write:
    //
    //   --lift-cf-to-scf      cf.br/cf.cond_br -> scf.if/scf.while
    //   --convert-scf-to-emitc  scf -> emitc.if/emitc.for
    //
    // TWO, NOT registerConversionPasses(). That registers every conversion
    // MLIR has - AMDGPU, ArmSME, SPIR-V - and each one is a link dependency,
    // so the tool failed to link on createConvertAMDGPUToROCDLPass before it
    // failed on anything relevant.
    mlir::registerLiftControlFlowToSCFPass();
    mlir::registerSCFToEmitC();
    // AND arith -> emitc, because --ctjs-lift-to-scf encodes its edge
    // multiplexers as arith i32 flags (Phase 62½-C).
    mlir::registerConvertArithToEmitC();
    // ctcompile::registerLoweringPasses() is Phase 10's and has no source yet.
    // The policy's snippet calls it; calling it here would not compile, and
    // stubbing it would be a registration that silently does nothing.
    return mlir::asMainReturnCode(
        mlir::MlirOptMain(argc, argv, "CTJS optimizer driver\n", registry));
}
