// ctjs-opt - the CTJS optimizer driver.
//
// BUILT BEFORE A SINGLE OPERATION EXISTS, which the policy asks for in as many
// words: "Build ctjs-opt in Phase 7, before defining a single operation. It is
// a thin MlirOptMain wrapper and it makes every subsequent phase testable." A
// dialect defined before its test driver cannot be validated, and the first
// fifty operations would then be written without feedback.
#include <ctcompile/Support/MLIRContextSetup.hpp>

#include "ctcompile/CTJS/Transforms/Passes.h"

#include "mlir/IR/DialectRegistry.h"
#include "mlir/Tools/mlir-opt/MlirOptMain.h"

int main(int argc, char ** argv) {
    mlir::DialectRegistry registry;
    ctcompile::registerCTCompileDialects(registry);
    // Generated by -gen-pass-decls; there are no passes yet and it registers
    // none, which is the honest state rather than a stub.
    ctcompile::ctjs::registerCTJSPasses();
    // ctcompile::registerLoweringPasses() is Phase 10's and has no source yet.
    // The policy's snippet calls it; calling it here would not compile, and
    // stubbing it would be a registration that silently does nothing.
    return mlir::asMainReturnCode(
        mlir::MlirOptMain(argc, argv, "CTJS optimizer driver\n", registry));
}
