// The rest of the property table, grouped by CSS module: every property the
// parsing and inheritance corpus tests that table.cpp's core set does not
// carry. Each row is the property's initial value and inheritance from its
// module's specification; the grammar is `freeform` until modelled, because
// a name absent from the table is an expando on `el.style` (CSSOM §6.7.2)
// and a property with no row has no initial value for getComputedStyle to
// publish - the two halves of `inheritance.html`.

#include "internal.hpp"

namespace ctbrowser::style::css {

using namespace detail;

namespace {

constexpr property_syntax modules[] = {
    // --- CSS Animations 1 and 2, Scroll-driven Animations ------------------
    {"animation-timing-function", k::freeform, "", "ease", false, false},
    {"animation-direction", k::keyword_only, "normal reverse alternate alternate-reverse", "normal",
     false, false},
    {"animation-fill-mode", k::keyword_only, "none forwards backwards both", "none", false, false},
    {"animation-play-state", k::keyword_only, "running paused", "running", false, false},
    {"animation-composition", k::keyword_only, "replace add accumulate", "replace", false, false},
    {"animation-range", k::freeform, "", "normal", false, false, true},
    {"animation-range-start", k::freeform, "", "normal", false, false},
    {"animation-range-end", k::freeform, "", "normal", false, false},
    {"transition-behavior", k::keyword_only, "normal allow-discrete", "normal", false, false},
    // --- CSS Transforms 2 ----------------------------------------------------
    {"backface-visibility", k::keyword_only, "visible hidden", "visible", false, false},
    {"perspective", k::length, "none", "none", false, true},
    {"perspective-origin", k::position, "", "50% 50%", false, false},
    {"transform-box", k::keyword_only, "content-box border-box fill-box stroke-box view-box",
     "view-box", false, false},
    {"transform-style", k::keyword_only, "flat preserve-3d", "flat", false, false},
    {"-webkit-transform", k::freeform, "", "none", false, false},
    {"-webkit-perspective", k::length, "none", "none", false, true},
    // --- Filter Effects, Compositing ------------------------------------------
    {"backdrop-filter", k::freeform, "", "none", false, false},
    {"flood-color", k::color, "", "rgb(0, 0, 0)", false, false},
    {"flood-opacity", k::number_percentage, "", "1", false, false},
    {"lighting-color", k::color, "", "rgb(255, 255, 255)", false, false},
    {"color-interpolation-filters", k::keyword_only, "auto srgb linearrgb", "linearrgb", true,
     false},
    {"background-blend-mode", k::freeform, "", "normal", false, false},
    {"mix-blend-mode", k::keyword_only,
     "normal multiply screen overlay darken lighten color-dodge color-burn hard-light soft-light "
     "difference exclusion hue saturation color luminosity plus-darker plus-lighter",
     "normal", false, false},
    {"isolation", k::keyword_only, "auto isolate", "auto", false, false},
    // --- CSS Masking, Shapes, Motion ------------------------------------------
    {"clip", k::freeform, "", "auto", false, false},
    {"clip-path", k::freeform, "", "none", false, false},
    {"clip-rule", k::keyword_only, "nonzero evenodd", "nonzero", true, false},
    {"mask", k::freeform, "", "none", false, false, true},
    {"mask-image", k::freeform, "", "none", false, false},
    {"mask-mode", k::freeform, "", "match-source", false, false},
    {"mask-repeat", k::freeform, "", "repeat", false, false},
    {"mask-position", k::freeform, "", "0% 0%", false, false},
    {"mask-clip", k::freeform, "", "border-box", false, false},
    {"mask-origin", k::freeform, "", "border-box", false, false},
    {"mask-size", k::freeform, "", "auto", false, false},
    {"mask-composite", k::freeform, "", "add", false, false},
    {"mask-type", k::keyword_only, "luminance alpha", "luminance", false, false},
    {"shape-outside", k::freeform, "", "none", false, false},
    {"shape-image-threshold", k::number_percentage, "", "0", false, false},
    {"offset", k::freeform, "", "normal", false, false, true},
    {"offset-anchor", k::freeform, "", "auto", false, false},
    {"offset-position", k::freeform, "", "normal", false, false},
    {"offset-rotate", k::freeform, "", "auto", false, false},
    // --- CSS Grid, Box Alignment ----------------------------------------------
    {"grid", k::freeform, "", "none", false, false, true},
    {"grid-template", k::freeform, "", "none", false, false, true},
    {"grid-template-columns", k::freeform, "", "none", false, false},
    {"grid-template-rows", k::freeform, "", "none", false, false},
    {"grid-template-areas", k::freeform, "", "none", false, false},
    {"grid-auto-columns", k::freeform, "", "auto", false, false},
    {"grid-auto-rows", k::freeform, "", "auto", false, false},
    {"grid-auto-flow", k::freeform, "", "row", false, false},
    {"grid-area", k::freeform, "", "auto", false, false, true},
    {"grid-row", k::freeform, "", "auto", false, false, true},
    {"grid-column", k::freeform, "", "auto", false, false, true},
    {"grid-row-start", k::freeform, "", "auto", false, false},
    {"grid-row-end", k::freeform, "", "auto", false, false},
    {"grid-column-start", k::freeform, "", "auto", false, false},
    {"grid-column-end", k::freeform, "", "auto", false, false},
    {"grid-gap", k::freeform, "", "normal", false, false, true},
    {"grid-row-gap", k::length_percentage, "normal", "normal", false, true},
    {"grid-column-gap", k::length_percentage, "normal", "normal", false, true},
    {"justify-items", k::freeform, "", "legacy", false, false},
    {"justify-self", k::freeform, "", "auto", false, false},
    {"place-content", k::freeform, "", "normal", false, false, true},
    {"place-items", k::freeform, "", "legacy", false, false, true},
    {"place-self", k::freeform, "", "auto", false, false, true},
    // --- CSS Multi-column, Fragmentation, Overflow ---------------------------
    {"columns", k::freeform, "", "auto", false, false, true},
    {"column-count", k::integer, "auto", "auto", false, true},
    {"column-width", k::length, "auto", "auto", false, true},
    {"column-fill", k::keyword_only, "auto balance balance-all", "balance", false, false},
    {"column-rule", k::freeform, "", "medium none currentcolor", false, false, true},
    {"column-rule-width", k::length, "thin medium thick", "medium", false, true},
    {"column-rule-style", k::keyword_only,
     "none hidden dotted dashed solid double groove ridge inset outset", "none", false, false},
    {"column-rule-color", k::color, "", "currentcolor", false, false},
    {"break-after", k::keyword_only,
     "auto avoid always all avoid-page page left right recto verso avoid-column column "
     "avoid-region region",
     "auto", false, false},
    {"break-before", k::keyword_only,
     "auto avoid always all avoid-page page left right recto verso avoid-column column "
     "avoid-region region",
     "auto", false, false},
    {"break-inside", k::keyword_only, "auto avoid avoid-page avoid-column avoid-region", "auto",
     false, false},
    {"box-decoration-break", k::keyword_only, "slice clone", "slice", false, false},
    {"page", k::freeform, "", "auto", false, false},
    {"overflow-block", k::keyword_only, "visible hidden clip scroll auto", "visible", false, false},
    {"overflow-inline", k::keyword_only, "visible hidden clip scroll auto", "visible", false,
     false},
    {"overflow-anchor", k::keyword_only, "auto none", "auto", false, false},
    {"overflow-clip-margin", k::freeform, "", "0px", false, false},
    {"block-ellipsis", k::freeform, "", "no-ellipsis", true, false},
    {"line-clamp", k::freeform, "", "none", false, false, true},
    {"-webkit-line-clamp", k::integer, "none", "none", false, true},
    {"continue", k::keyword_only, "normal discard collapse -webkit-legacy", "normal", false, false},
    {"scrollbar-gutter", k::freeform, "", "auto", false, false},
    {"scrollbar-width", k::keyword_only, "auto thin none", "auto", false, false},
    {"scrollbar-color", k::freeform, "", "auto", true, false},
    {"scroll-behavior", k::keyword_only, "auto smooth", "auto", false, false},
    {"scroll-marker-group", k::keyword_only, "none before after", "none", false, false},
    {"scroll-target-group", k::keyword_only, "none auto", "none", false, false},
    // --- CSS Scroll Snap --------------------------------------------------------
    {"scroll-snap-type", k::freeform, "", "none", false, false},
    {"scroll-snap-align", k::freeform, "", "none", false, false},
    {"scroll-snap-stop", k::keyword_only, "normal always", "normal", false, false},
    {"scroll-margin", k::freeform, "", "0px", false, false, true},
    {"scroll-margin-block", k::freeform, "", "0px", false, false, true},
    {"scroll-margin-inline", k::freeform, "", "0px", false, false, true},
    {"scroll-margin-top", k::length, "", "0px", false, false},
    {"scroll-margin-right", k::length, "", "0px", false, false},
    {"scroll-margin-bottom", k::length, "", "0px", false, false},
    {"scroll-margin-left", k::length, "", "0px", false, false},
    {"scroll-margin-block-start", k::length, "", "0px", false, false},
    {"scroll-margin-block-end", k::length, "", "0px", false, false},
    {"scroll-margin-inline-start", k::length, "", "0px", false, false},
    {"scroll-margin-inline-end", k::length, "", "0px", false, false},
    {"scroll-padding", k::freeform, "", "auto", false, false, true},
    {"scroll-padding-block", k::freeform, "", "auto", false, false, true},
    {"scroll-padding-inline", k::freeform, "", "auto", false, false, true},
    {"scroll-padding-block-start", k::length_percentage, "auto", "auto", false, true},
    {"scroll-padding-block-end", k::length_percentage, "auto", "auto", false, true},
    {"scroll-padding-inline-start", k::length_percentage, "auto", "auto", false, true},
    {"scroll-padding-inline-end", k::length_percentage, "auto", "auto", false, true},
    {"overscroll-behavior", k::freeform, "", "auto", false, false, true},
    {"overscroll-behavior-x", k::keyword_only, "contain none auto", "auto", false, false},
    {"overscroll-behavior-y", k::keyword_only, "contain none auto", "auto", false, false},
    {"overscroll-behavior-block", k::keyword_only, "contain none auto", "auto", false, false},
    {"overscroll-behavior-inline", k::keyword_only, "contain none auto", "auto", false, false},
    // --- CSS Logical, Sizing, Box ----------------------------------------------
    {"min-inline-size", k::length_percentage, "auto min-content max-content fit-content stretch",
     "0px", false, true},
    {"min-block-size", k::length_percentage, "auto min-content max-content fit-content stretch",
     "0px", false, true},
    {"max-inline-size", k::length_percentage, "none min-content max-content fit-content stretch",
     "none", false, true},
    {"max-block-size", k::length_percentage, "none min-content max-content fit-content stretch",
     "none", false, true},
    {"border-block", k::freeform, "", "medium none currentcolor", false, false, true},
    {"border-block-start", k::freeform, "", "medium none currentcolor", false, false, true},
    {"border-block-end", k::freeform, "", "medium none currentcolor", false, false, true},
    {"border-inline", k::freeform, "", "medium none currentcolor", false, false, true},
    {"border-inline-start", k::freeform, "", "medium none currentcolor", false, false, true},
    {"border-inline-end", k::freeform, "", "medium none currentcolor", false, false, true},
    {"border-block-color", k::freeform, "", "currentcolor", false, false, true},
    {"border-block-style", k::freeform, "", "none", false, false, true},
    {"border-block-width", k::freeform, "", "medium", false, false, true},
    {"border-inline-color", k::freeform, "", "currentcolor", false, false, true},
    {"border-inline-style", k::freeform, "", "none", false, false, true},
    {"border-inline-width", k::freeform, "", "medium", false, false, true},
    {"border-start-start-radius", k::freeform, "", "0px", false, false},
    {"border-start-end-radius", k::freeform, "", "0px", false, false},
    {"border-end-start-radius", k::freeform, "", "0px", false, false},
    {"border-end-end-radius", k::freeform, "", "0px", false, false},
    {"-webkit-border-radius", k::freeform, "", "0px", false, false, true},
    {"-webkit-border-top-left-radius", k::freeform, "", "0px", false, false},
    {"-webkit-border-top-right-radius", k::freeform, "", "0px", false, false},
    {"-webkit-border-bottom-right-radius", k::freeform, "", "0px", false, false},
    {"-webkit-border-bottom-left-radius", k::freeform, "", "0px", false, false},
    {"margin-trim", k::freeform, "", "none", false, false},
    {"contain", k::freeform, "", "none", false, false},
    {"will-change", k::freeform, "", "auto", false, false},
    {"field-sizing", k::keyword_only, "fixed content", "fixed", false, false},
    {"interactivity", k::keyword_only, "auto inert", "auto", true, false},
    {"appearance", k::freeform, "", "none", false, false},
    // --- CSS Fonts 4 ---------------------------------------------------------------
    {"font-kerning", k::keyword_only, "auto normal none", "auto", true, false},
    {"font-language-override", k::freeform, "", "normal", true, false},
    {"font-optical-sizing", k::keyword_only, "auto none", "auto", true, false},
    {"font-synthesis", k::freeform, "", "weight style small-caps position", true, false, true},
    {"font-synthesis-weight", k::keyword_only, "auto none", "auto", true, false},
    {"font-synthesis-style", k::keyword_only, "auto none oblique-only", "auto", true, false},
    {"font-synthesis-small-caps", k::keyword_only, "auto none", "auto", true, false},
    {"font-synthesis-position", k::keyword_only, "auto none", "auto", true, false},
    {"font-variant-caps", k::keyword_only,
     "normal small-caps all-small-caps petite-caps all-petite-caps unicase titling-caps", "normal",
     true, false},
    {"font-variant-east-asian", k::freeform, "", "normal", true, false},
    {"font-variant-emoji", k::keyword_only, "normal text emoji unicode", "normal", true, false},
    {"font-variant-ligatures", k::freeform, "", "normal", true, false},
    {"font-variant-numeric", k::freeform, "", "normal", true, false},
    {"font-variant-position", k::keyword_only, "normal sub super", "normal", true, false},
    // --- CSS Text 4, Text Decoration 4, Inline, Ruby, Writing Modes ----------------
    {"text-align-all", k::keyword_only, "start end left right center justify match-parent", "start",
     true, false},
    {"text-align-last", k::keyword_only, "auto start end left right center justify match-parent",
     "auto", true, false},
    {"text-justify", k::keyword_only, "auto none inter-word inter-character distribute", "auto",
     true, false},
    {"text-wrap", k::freeform, "", "wrap", true, false, true},
    {"text-wrap-mode", k::keyword_only, "wrap nowrap", "wrap", true, false},
    {"text-wrap-style", k::keyword_only, "auto balance stable pretty avoid-orphans", "auto", true,
     false},
    {"white-space-collapse", k::keyword_only,
     "collapse preserve preserve-breaks preserve-spaces break-spaces", "collapse", true, false},
    {"word-wrap", k::keyword_only, "normal break-word anywhere", "normal", true, false},
    {"line-break", k::keyword_only, "auto loose normal strict anywhere", "auto", true, false},
    {"hyphens", k::keyword_only, "none manual auto", "manual", true, false},
    {"hyphenate-character", k::freeform, "", "auto", true, false},
    {"hanging-punctuation", k::freeform, "", "none", true, false},
    {"text-autospace", k::freeform, "", "normal", true, false},
    {"text-spacing-trim", k::keyword_only,
     "normal auto space-all trim-both trim-all trim-start space-first", "normal", true, false},
    {"text-size-adjust", k::percentage, "auto none", "auto", true, true},
    {"text-combine-upright", k::freeform, "", "none", true, false},
    {"text-orientation", k::keyword_only, "mixed upright sideways", "mixed", true, false},
    {"text-decoration-skip-ink", k::keyword_only, "auto none all", "auto", true, false},
    {"text-underline-position", k::freeform, "", "auto", true, false}, // keywords.cpp
    {"text-emphasis", k::freeform, "", "none currentcolor", true, false, true},
    {"text-emphasis-style", k::freeform, "", "none", true, false},
    {"text-emphasis-color", k::color, "", "currentcolor", true, false},
    {"text-emphasis-position", k::freeform, "", "auto", true, false},
    {"initial-letters", k::freeform, "", "normal", false, false},
    {"initial-letters-align", k::freeform, "", "alphabetic", true, false},
    {"initial-letters-wrap", k::freeform, "", "none", true, false},
    {"alignment-baseline", k::keyword_only,
     "baseline text-bottom alphabetic ideographic middle central mathematical text-top", "baseline",
     false, false},
    {"dominant-baseline", k::keyword_only,
     "auto text-bottom alphabetic ideographic middle central mathematical hanging text-top", "auto",
     true, false},
    {"baseline-shift", k::length_percentage, "sub super top center bottom", "0px", false, false},
    {"ruby-align", k::keyword_only, "start center space-between space-around", "space-around", true,
     false},
    {"ruby-merge", k::keyword_only, "separate merge auto", "separate", true, false},
    {"ruby-overhang", k::keyword_only, "auto none", "auto", true, false},
    {"ruby-position", k::freeform, "", "alternate", true, false},
    {"quotes", k::freeform, "", "auto", true, false},
    // --- CSS Lists, Generated Content -------------------------------------------------
    {"counter-increment", k::freeform, "", "none", false, false},
    {"counter-reset", k::freeform, "", "none", false, false},
    {"counter-set", k::freeform, "", "none", false, false},
    {"bookmark-level", k::freeform, "", "none", false, false},
    {"bookmark-state", k::keyword_only, "open closed", "open", false, false},
    // --- CSS Color Adjust, Images, UI ---------------------------------------------------
    {"color-scheme", k::freeform, "", "normal", true, false},
    {"color-adjust", k::keyword_only, "economy exact", "economy", true, false},
    {"print-color-adjust", k::keyword_only, "economy exact", "economy", true, false},
    {"forced-color-adjust", k::keyword_only, "auto none preserve-parent-color", "auto", true,
     false},
    {"dynamic-range-limit", k::freeform, "", "no-limit", true, false},
    {"image-orientation", k::keyword_only, "from-image none", "from-image", true, false},
    {"image-rendering", k::keyword_only, "auto smooth high-quality pixelated crisp-edges", "auto",
     true, false},
    {"image-resolution", k::freeform, "", "1dppx", true, false},
    {"caret-shape", k::keyword_only, "auto bar block underscore", "auto", true, false},
    {"nav-up", k::freeform, "", "auto", false, false},
    {"nav-down", k::freeform, "", "auto", false, false},
    {"nav-left", k::freeform, "", "auto", false, false},
    {"nav-right", k::freeform, "", "auto", false, false},
    {"link-parameters", k::freeform, "", "none", false, false},
    // --- CSS Anchor Positioning, View Transitions, Exclusions ---------------------------
    {"anchor-scope", k::freeform, "", "none", false, false},
    {"position-try", k::freeform, "", "none", false, false, true},
    {"position-try-fallbacks", k::freeform, "", "none", false, false},
    {"position-try-order", k::keyword_only,
     "normal most-width most-height most-block-size most-inline-size", "normal", false, false},
    {"position-visibility", k::freeform, "", "always", false, false},
    {"view-transition-class", k::freeform, "", "none", false, false},
    {"view-transition-group", k::freeform, "", "normal", false, false},
    {"wrap-flow", k::keyword_only, "auto both start end minimum maximum clear", "auto", false,
     false},
    {"wrap-through", k::keyword_only, "wrap none", "wrap", false, false},
    {"initial-sizing", k::freeform, "", "normal", false, false},
    // --- CSS Rhythm -----------------------------------------------------------------------
    {"block-step", k::freeform, "", "none", false, false, true},
    {"block-step-size", k::length, "none", "none", false, true},
    {"block-step-insert", k::keyword_only, "margin-box padding-box content-box", "margin-box",
     false, false},
    {"block-step-align", k::keyword_only, "auto center start end", "auto", false, false},
    {"block-step-round", k::keyword_only, "up down nearest", "up", false, false},
};

} // namespace

namespace detail {

std::span<const property_syntax> module_properties() noexcept {
    return std::span<const property_syntax>{modules, std::size(modules)};
}

} // namespace detail

} // namespace ctbrowser::style::css
