# THE TABLE THAT INSTALLS A GENERATED TRANSLATION UNIT'S BODIES.
#
# `compile-js-to-cpp.cmake` beside this produces the compiled bodies and stops
# there: it renames a handful of entries to fixed symbols so that a driver can
# DECLARE them, which is what a differential harness wants and what a generated
# application cannot use - an application has nobody to write the declarations.
#
# So this reads the emitted C++ and writes the other half: one `extern "C"`
# declaration per compiled body and one `ctcompile::aot::entry_table` naming
# them all. The application then installs its own bodies at startup with no
# hand-written list anywhere.
#
# IT READS THE EMITTED C++ AND NOT THE MLIR, and that is the point rather than
# convenience. The definitive list of what this build can install is the list of
# symbols that actually EXIST in the object file; a function the backend refused
# leaves no definition, and a table generated from an earlier stage would name
# it and fail at link with an undefined symbol instead of being one row shorter.
# The refusal is a fact about the build, and this is downstream of it.
#
# Required: -DGENERATED= -DOUTPUT= -DTABLE=   Optional: -DSOURCE_NAME=
cmake_minimum_required(VERSION 3.20)

foreach(required GENERATED OUTPUT TABLE)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "aot-entry-table.cmake: -D${required}= is required")
  endif()
endforeach()
if(NOT DEFINED SOURCE_NAME)
  set(SOURCE_NAME "<unnamed>")
endif()

file(READ "${GENERATED}" emitted)

# THE ENTRY SIGNATURE IS THE MATCH, not merely `extern "C"`. The backend emits
# the two boxing shims into an anonymous namespace and a memo byte per entry as
# a file-scope `static const char`, and a looser pattern would collect those and
# then fail to compile the declarations it wrote for them. Anchoring on the
# first ABI parameter means only a `ct_aot_entry_fn` is picked up, which is
# exactly what the table may hold.
string(REGEX MATCHALL "extern \"C\" int32_t [A-Za-z_][A-Za-z0-9_]*\\(ctbrowser::aot::ct_aot_ctx\\*"
       found "${emitted}")

list(LENGTH found how_many)
if(how_many EQUAL 0)
  message(FATAL_ERROR
    "aot-entry-table.cmake: ${GENERATED} defines no compiled entry. Either the backend refused "
    "every function - run ctjs-opt --ctjs-lower-to-emitc and read the ctjs.not_lowered attribute "
    "it leaves behind - or the shape of an emitted entry has changed and this pattern no longer "
    "matches it.")
endif()

# A SEMICOLON, THROUGH A VARIABLE. CMake's list separator IS the semicolon, and
# every way of writing one literally inside a quoted string - escaped or not -
# either splits the argument or survives into the output as `\;`. Both were
# tried; this is the spelling that emits a semicolon and nothing else.
set(semi ";")

set(declarations "")
set(rows "")
set(symbols "")
foreach(one IN LISTS found)
  string(REGEX REPLACE "^extern \"C\" int32_t ([A-Za-z_][A-Za-z0-9_]*)\\(.*$" "\\1" symbol "${one}")
  # A DUPLICATE WOULD BE A DUPLICATE DEFINITION and the link would say so, but
  # it would say so about the generated file rather than about this one, and the
  # message would not mention that a table was involved.
  if(symbol IN_LIST symbols)
    message(FATAL_ERROR "aot-entry-table.cmake: ${GENERATED} defines ${symbol} twice")
  endif()
  # THE DECLARATION IS SPELLED AS aot_entry.h SPELLS THE TYPEDEF, so that taking
  # its address yields a ct_aot_entry_fn with no cast. A cast here would compile
  # whatever the emitted signature turned into.
  string(APPEND declarations
    "std::int32_t ${symbol}(\n"
    "    ctbrowser::aot::ct_aot_ctx *, const ctbrowser::aot::ct_aot_site *, const std::uint64_t *,\n"
    "    std::uint32_t, std::uint64_t, std::uint32_t, std::uint64_t *)${semi}\n")
  string(APPEND rows "    {\"${symbol}\", &${symbol}},\n")
  list(APPEND symbols "${symbol}")
endforeach()

# THE COUNT COMES FROM THE ROWS, not from the matches. They are the same number
# today because nothing is skipped, and a table whose declared length is one
# more than its array is a read past the end of it - which is not the kind of
# defect to leave one edit away.
list(LENGTH symbols how_many)

file(WRITE "${OUTPUT}"
"// GENERATED BY ctcompile/test/aot-entry-table.cmake - DO NOT EDIT.
//
// One row per compiled body in ${SOURCE_NAME}, keyed by the symbol the backend
// emitted. ctcompile::aot::install matches each against the naming rule the
// importer used, so nothing here has to say which function_proto it is for -
// the index is in the name.
#include <ctcompile/AOT/EntryTable.hpp>

#include <cstdint>

extern \"C\" {
${declarations}}

namespace {

const ctcompile::aot::entry_binding ctc_entry_rows[] = {
${rows}};

} // namespace

// `extern`, AND IT IS NOT DECORATION. A namespace-scope `const` object has
// INTERNAL linkage in C++, so without this the table is invisible to the
// launcher that declares it and the compiler reports it as an unused variable -
// which under this project's -Werror is where the mistake surfaces, one step
// before the link error it would otherwise become.
extern const ctcompile::aot::entry_table ${TABLE};
const ctcompile::aot::entry_table ${TABLE} = {
    \"${SOURCE_NAME}\", ctc_entry_rows, ${how_many}u};
")

message(STATUS "aot-entry-table.cmake: ${how_many} compiled entr(y/ies) from ${SOURCE_NAME}")
