#include <ctbrowser/shell/embedded_fonts.hpp>

// The OFL faces as bytes in the binary, or nothing at all.
//
// Two conditions have to hold, and both are checked rather than assumed: the
// compiler must understand `#embed`, and the fonts must be on its embed search
// path (CMake puts them there with --embed-dir). If either fails this file
// still compiles - to a function that registers nothing - and the caller reads
// the directory instead.
//
// `#embed <name>` rather than `#embed "name"`: the quoted form searches
// relative to THIS source file and ignores --embed-dir, which is a different
// search path from the one -I feeds. That difference costs an afternoon if you
// assume it works like #include.

// clang-format off
#ifdef __has_embed
#  if __has_embed(<Tinos-Regular.ttf>) == 1
#    define CTBROWSER_HAVE_EMBEDDED_FONTS 1
#  endif
#endif
// clang-format on

#ifdef CTBROWSER_HAVE_EMBEDDED_FONTS
#include <array>
#include <cstddef>
#include <span>
#include <string>

// `#embed` is C23; in C++23 clang accepts it as an extension and -pedantic
// -Werror turns that into an error. Silenced HERE and nowhere else - the
// warning is right about the rest of the tree, which is C++23 and should stay
// that way.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wc23-extensions"

namespace {

// Spelled out rather than generated by a macro: `#embed` is a directive and a
// macro cannot expand to one, so twelve blocks is what twelve faces costs.
//
// THE FENCE BELOW IS LOAD-BEARING. clang-format reads the angle brackets as
// comparison operators and respaces the line into `#embed <Tinos-Bold.ttf>`,
// which is not a filename any more. The directive is invisible to the default
// build - embedding is off there - so the damage surfaces only in the one
// configuration that uses it, which is the worst place for it to hide.
// clang-format off
const unsigned char tinos_regular[] = {
#embed <Tinos-Regular.ttf>
};
const unsigned char tinos_bold[] = {
#embed <Tinos-Bold.ttf>
};
const unsigned char tinos_italic[] = {
#embed <Tinos-Italic.ttf>
};
const unsigned char tinos_bold_italic[] = {
#embed <Tinos-BoldItalic.ttf>
};
const unsigned char fira_regular[] = {
#embed <FiraSans-Regular.ttf>
};
const unsigned char fira_bold[] = {
#embed <FiraSans-Bold.ttf>
};
const unsigned char fira_italic[] = {
#embed <FiraSans-Italic.ttf>
};
const unsigned char fira_bold_italic[] = {
#embed <FiraSans-BoldItalic.ttf>
};
const unsigned char cousine_regular[] = {
#embed <Cousine-Regular.ttf>
};
const unsigned char cousine_bold[] = {
#embed <Cousine-Bold.ttf>
};
const unsigned char cousine_italic[] = {
#embed <Cousine-Italic.ttf>
};
const unsigned char cousine_bold_italic[] = {
#embed <Cousine-BoldItalic.ttf>
};
// clang-format on

#pragma clang diagnostic pop

struct baked {
    std::string_view file; // the name use_real_fonts builds, minus the directory
    std::span<const unsigned char> bytes;
};

constexpr std::array<baked, 12> faces{{
    {"Tinos-Regular.ttf", tinos_regular},
    {"Tinos-Bold.ttf", tinos_bold},
    {"Tinos-Italic.ttf", tinos_italic},
    {"Tinos-BoldItalic.ttf", tinos_bold_italic},
    {"FiraSans-Regular.ttf", fira_regular},
    {"FiraSans-Bold.ttf", fira_bold},
    {"FiraSans-Italic.ttf", fira_italic},
    {"FiraSans-BoldItalic.ttf", fira_bold_italic},
    {"Cousine-Regular.ttf", cousine_regular},
    {"Cousine-Bold.ttf", cousine_bold},
    {"Cousine-Italic.ttf", cousine_italic},
    {"Cousine-BoldItalic.ttf", cousine_bold_italic},
}};

} // namespace
#endif

namespace ctbrowser::shell {

bool have_embedded_fonts() noexcept {
#ifdef CTBROWSER_HAVE_EMBEDDED_FONTS
    return true;
#else
    return false;
#endif
}

std::size_t register_embedded_fonts([[maybe_unused]] asset_registry & into,
                                    [[maybe_unused]] std::string_view directory) {
#ifdef CTBROWSER_HAVE_EMBEDDED_FONTS
    std::size_t registered = 0;
    for (const auto & face : faces) {
        std::vector<std::byte> bytes(face.bytes.size());
        for (std::size_t i = 0; i < face.bytes.size(); ++i) {
            bytes[i] = static_cast<std::byte>(face.bytes[i]);
        }
        // Under the name the loader will ask for, so nothing downstream has to
        // know whether a face came from the binary or the disk.
        into.add(std::string{directory} + "/" + std::string{face.file}, std::move(bytes));
        ++registered;
    }
    return registered;
#else
    return 0;
#endif
}

} // namespace ctbrowser::shell
