#include "ctcompile/CTJS/IR/CTJSOps.h"

#include "mlir/IR/BuiltinAttributes.h"
#include "llvm/ADT/STLExtras.h"

namespace ctcompile::ctjs {

void TryOp::getSuccessorRegions(mlir::RegionBranchPoint point,
                                llvm::SmallVectorImpl<mlir::RegionSuccessor> & regions) {
    if (point.isParent()) {
        regions.emplace_back(&getBody());
        return;
    }
    auto terminator = point.getTerminatorPredecessorOrNull();
    if (llvm::isa<TryExitOp>(terminator.getOperation())) { regions.emplace_back(&getCatchBody()); }
    regions.emplace_back(getOperation());
}

mlir::ValueRange TryOp::getSuccessorInputs(mlir::RegionSuccessor successor) {
    if (auto * region = successor.getSuccessor()) {
        return region->empty() ? mlir::ValueRange{} : region->front().getArguments();
    }
    return getOperation()->getResults();
}

void TryOp::getRegionInvocationBounds(llvm::ArrayRef<mlir::Attribute>,
                                      llvm::SmallVectorImpl<mlir::InvocationBounds> & bounds) {
    bounds.emplace_back(1, 1);
    bounds.emplace_back(0, 1);
}

mlir::LogicalResult TryOp::verify() {
    if (!llvm::hasSingleElement(getBody()) || !llvm::hasSingleElement(getCatchBody()) ||
        getBody().front().empty() || getCatchBody().front().empty()) {
        return emitOpError("requires a nonempty block in each try and catch region");
    }
    if (!getBody().front().getArguments().empty() ||
        getCatchBody().front().getNumArguments() == 0) {
        return emitOpError("requires an argument-free body and a catch payload argument");
    }
    for (auto argument : getCatchBody().front().getArguments()) {
        if (!llvm::isa<ValueType>(argument.getType())) {
            return emitOpError("catch arguments must be JavaScript values");
        }
    }
    if (!llvm::isa<TryExitOp>(getBody().front().getTerminator()) ||
        !llvm::isa<TryYieldOp>(getCatchBody().front().getTerminator())) {
        return emitOpError("requires try_exit in the body and try_yield in the catch");
    }
    return mlir::success();
}

mlir::MutableOperandRange TryExitOp::getMutableSuccessorOperands(mlir::RegionSuccessor point) {
    if (point.isRegion()) {
        return mlir::MutableOperandRange(getOperation(), 2, getNumOperands() - 2);
    }
    return mlir::MutableOperandRange(getOperation(), 1, 1);
}

void TryExitOp::getSuccessorRegions(llvm::ArrayRef<mlir::Attribute> operands,
                                    llvm::SmallVectorImpl<mlir::RegionSuccessor> & regions) {
    auto parent = llvm::cast<TryOp>((*this)->getParentOp());
    const auto flag = operands.empty()
                          ? mlir::IntegerAttr{}
                          : llvm::dyn_cast_or_null<mlir::IntegerAttr>(operands.front());
    if (!flag || !flag.getValue().isZero()) { regions.emplace_back(&parent.getCatchBody()); }
    if (!flag || flag.getValue().isZero()) { regions.emplace_back(parent.getOperation()); }
}

mlir::LogicalResult TryExitOp::verify() {
    auto parent = llvm::dyn_cast<TryOp>((*this)->getParentOp());
    if (!parent || (*this)->getParentRegion() != &parent.getBody()) {
        return emitOpError("must terminate a try body");
    }
    if (parent.getCatchBody().empty() ||
        getCaughtValues().size() != parent.getCatchBody().front().getNumArguments()) {
        return emitOpError("must carry the payload and every catch state value");
    }
    return mlir::success();
}

mlir::MutableOperandRange TryYieldOp::getMutableSuccessorOperands(mlir::RegionSuccessor) {
    return mlir::MutableOperandRange(getOperation());
}

mlir::LogicalResult TryYieldOp::verify() {
    auto parent = llvm::dyn_cast<TryOp>((*this)->getParentOp());
    if (!parent || (*this)->getParentRegion() != &parent.getCatchBody()) {
        return emitOpError("must terminate a catch body");
    }
    return mlir::success();
}

void InvokeOp::getSuccessorRegions(mlir::RegionBranchPoint point,
                                   llvm::SmallVectorImpl<mlir::RegionSuccessor> & regions) {
    if (point.isParent()) {
        regions.emplace_back(&getBody());
    } else if (llvm::isa<InvokeExitOp>(point.getTerminatorPredecessorOrNull().getOperation())) {
        regions.emplace_back(&getNormalBody());
        regions.emplace_back(&getUnwindBody());
    } else {
        regions.emplace_back(getOperation());
    }
}

mlir::ValueRange InvokeOp::getSuccessorInputs(mlir::RegionSuccessor successor) {
    if (auto * region = successor.getSuccessor()) {
        if (region->empty()) { return {}; }
        auto arguments = region->front().getArguments();
        // The thrown payload is generated by the exceptional completion, not
        // forwarded from a normal-result SSA operand. Sparse analyses handle
        // this non-successor input through their dedicated interface hook.
        if (region == &getUnwindBody() && !arguments.empty()) { return arguments.drop_front(); }
        return arguments;
    }
    return getResults();
}

void InvokeOp::getRegionInvocationBounds(llvm::ArrayRef<mlir::Attribute>,
                                         llvm::SmallVectorImpl<mlir::InvocationBounds> & bounds) {
    bounds.emplace_back(1, 1);
    bounds.emplace_back(0, 1);
    bounds.emplace_back(0, 1);
}

mlir::LogicalResult InvokeOp::verify() {
    for (auto & region : (*this)->getRegions()) {
        if (!llvm::hasSingleElement(region) || region.front().empty()) {
            return emitOpError("requires a nonempty block in each invocation region");
        }
        for (auto argument : region.front().getArguments()) {
            if (!llvm::isa<ValueType>(argument.getType())) {
                return emitOpError("continuation arguments must be JavaScript values");
            }
        }
    }
    if (!getBody().front().getArguments().empty() ||
        getNormalBody().front().getNumArguments() != 1 ||
        getUnwindBody().front().getNumArguments() == 0) {
        return emitOpError("requires an argument-free call body, one normal result argument "
                           "and an unwind payload argument");
    }
    auto & body = getBody().front();
    if (body.getOperations().size() != 2 || !llvm::isa<CallDirectOp>(body.front()) ||
        !llvm::isa<InvokeExitOp>(body.back())) {
        return emitOpError("requires exactly one call_direct followed by invoke_exit");
    }
    if (!llvm::isa<InvokeYieldOp>(getNormalBody().front().back()) ||
        !llvm::isa<InvokeYieldOp>(getUnwindBody().front().back())) {
        return emitOpError("requires invoke_yield in both continuations");
    }
    return mlir::success();
}

mlir::MutableOperandRange InvokeExitOp::getMutableSuccessorOperands(mlir::RegionSuccessor point) {
    auto parent = llvm::cast<InvokeOp>((*this)->getParentOp());
    if (point.getSuccessor() == &parent.getUnwindBody()) { return getStateMutable(); }
    return mlir::MutableOperandRange(getOperation(), 0, 1);
}

mlir::LogicalResult InvokeExitOp::verify() {
    auto parent = llvm::dyn_cast<InvokeOp>((*this)->getParentOp());
    if (!parent || (*this)->getParentRegion() != &parent.getBody()) {
        return emitOpError("must terminate an invocation call body");
    }
    auto call = llvm::dyn_cast_or_null<CallDirectOp>((*this)->getPrevNode());
    if (!call || getNormalResult() != call.getResult()) {
        return emitOpError("must dispatch the immediately preceding call_direct result");
    }
    if (!call.getResult().hasOneUse()) {
        return emitOpError("call result must be used only by normal completion dispatch");
    }
    for (auto state : getState()) {
        if (parent.getBody().isAncestor(state.getParentRegion())) {
            return emitOpError("unwind state must be defined before the invocation body");
        }
    }
    if (parent.getUnwindBody().empty() ||
        parent.getUnwindBody().front().getNumArguments() != getState().size() + 1) {
        return emitOpError("must carry every unwind state value after its implicit payload");
    }
    return mlir::success();
}

mlir::MutableOperandRange InvokeYieldOp::getMutableSuccessorOperands(mlir::RegionSuccessor) {
    return getValuesMutable();
}

mlir::LogicalResult InvokeYieldOp::verify() {
    auto parent = llvm::dyn_cast<InvokeOp>((*this)->getParentOp());
    if (!parent || ((*this)->getParentRegion() != &parent.getNormalBody() &&
                    (*this)->getParentRegion() != &parent.getUnwindBody())) {
        return emitOpError("must terminate a normal or unwind invocation continuation");
    }
    if (getValues().size() != parent.getNumResults()) {
        return emitOpError("must supply every invocation result");
    }
    return mlir::success();
}

} // namespace ctcompile::ctjs
