# Both normal native entry settings and the explicit disabled baseline must
# compile standalone and agree with the interpreter on effects and primitives.
cmake_minimum_required(VERSION 3.20)
foreach(required TRANSLATE OPT SOURCE CXX NM REFERENCE VM_LINKED WORK)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "check-native-optimization-defaults.cmake: -D${required}= is required")
  endif()
endforeach()
set(_work "${WORK}/native-optimization-defaults")
file(MAKE_DIRECTORY "${_work}")
foreach(_mode enabled disabled no-precompute no-prune explicit-precompute)
  set(_options -DOPTIMIZATION_REPORT=ON)
  if(_mode STREQUAL "disabled")
    list(APPEND _options -DOPTIMIZE=OFF)
  elseif(_mode STREQUAL "no-precompute")
    list(APPEND _options -DPRECOMPUTE=OFF)
  elseif(_mode STREQUAL "no-prune")
    list(APPEND _options -DPRUNE_UNREACHABLE=OFF)
  elseif(_mode STREQUAL "explicit-precompute")
    list(APPEND _options -DOPTIMIZE=OFF -DPRECOMPUTE=ON)
  endif()
  set(_module "${_work}/${_mode}.mlir")
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -DTRANSLATE=${TRANSLATE} -DOPT=${OPT}
      -DSOURCE=${SOURCE} -DOUTPUT=${_module} ${_options}
      -P "${CMAKE_CURRENT_LIST_DIR}/native-pipeline.cmake"
    RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "${_mode}: native pipeline failed\n${_out}${_err}")
  endif()
  file(READ "${_module}" _ir)
  if(_mode STREQUAL "enabled")
    if(NOT _ir MATCHES "ctnative.precompute_summary = \\{[^}]*expressions = [1-9][0-9]* : i64")
      message(FATAL_ERROR "native defaults did not precompute expressions\n${_out}${_err}")
    endif()
    if(NOT _ir MATCHES "ctnative.reachability_summary")
      message(FATAL_ERROR "native defaults did not run reachability")
    endif()
    string(REGEX MATCH "ctnative.precompute_summary = \\{[^}]*\\}" _summary "${_ir}")
    message(STATUS "${_summary}")
  elseif(_mode STREQUAL "disabled")
    if(_ir MATCHES "ctnative.(precompute|reachability)_summary")
      message(FATAL_ERROR "disabled baseline unexpectedly ran a default optimization")
    endif()
  elseif(_mode STREQUAL "no-precompute")
    if(_ir MATCHES "ctnative.precompute_summary" OR NOT _ir MATCHES "ctnative.reachability_summary")
      message(FATAL_ERROR "PRECOMPUTE=OFF did not disable only precomputation")
    endif()
  else()
    if(NOT _ir MATCHES "ctnative.precompute_summary" OR _ir MATCHES "ctnative.reachability_summary")
      message(FATAL_ERROR "${_mode}: expected precomputation without reachability")
    endif()
  endif()
  if(_ir MATCHES "ctnative.(specialized_from|partial_evaluated|supercompile_summary|deforest_summary)")
    message(FATAL_ERROR "native defaults unexpectedly enabled an opt-in transformation")
  endif()
  if(NOT _mode STREQUAL "enabled" AND NOT _mode STREQUAL "disabled")
    continue()
  endif()
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -DTRANSLATE=${TRANSLATE} -DMODULE=${_module}
      -DJS=${SOURCE} -DCXX=${CXX} -DNM=${NM} -DREFERENCE=${REFERENCE}
      -DVM_LINKED=${VM_LINKED} -DWORK=${_work} -DNAME=defaults-${_mode}
      -P "${CMAKE_CURRENT_LIST_DIR}/check-native-unit.cmake"
    RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
  if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "${_mode}: native differential failed\n${_out}${_err}")
  endif()
  message(STATUS "${_out}")
  file(READ "${_work}/native-unit-defaults-${_mode}/unit.cpp" _cpp_${_mode})
  string(LENGTH "${_cpp_${_mode}}" _bytes_${_mode})
  execute_process(
    COMMAND "${_work}/native-unit-defaults-${_mode}/unit"
    RESULT_VARIABLE _rc OUTPUT_VARIABLE _observed_${_mode} ERROR_VARIABLE _err)
  if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "${_mode}: native binary failed (${_rc})\n${_err}")
  endif()
endforeach()
set(_expected "answer=42\nliteralNaNEqual=0\nliteralStringEqual=1\nnegativeInfinity=-inf\nobserved=122\nruntimeNaNEqual=0\nruntimeNumberEqual=1\ntrace=122\n")
if(NOT _observed_enabled STREQUAL _expected OR NOT _observed_disabled STREQUAL _expected)
  message(FATAL_ERROR "defaults changed the expected observations\nenabled:\n${_observed_enabled}disabled:\n${_observed_disabled}")
endif()
if(_cpp_enabled STREQUAL _cpp_disabled)
  message(FATAL_ERROR "default and disabled generated C++ are identical; this fixture did not exercise the policy")
endif()
message(STATUS "native defaults: 8 observations agree with the disabled baseline; generated C++ ${_bytes_disabled} -> ${_bytes_enabled} bytes")
