  foreach(_line IN LISTS _recording_lines)
    if(_line MATCHES "^program ([0-9a-f]+) ")
      set(_program_hash "${CMAKE_MATCH_1}")
    elseif(_line MATCHES "^fn ([0-9]+) .* name ([^ ]+)$")
      set(_function_index "${CMAKE_MATCH_1}")
      set(_function_name "${CMAKE_MATCH_2}")
    elseif(_function_name MATCHES "^global(AliasJoin|AliasLoop|RetainedContainer|ReplacedPublication)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected publication observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _publication_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^spreadRetained(Call|Construct|Receiver)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind (obj|arr) made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected spread observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_kind "${CMAKE_MATCH_2}")
      set(_row "${_function_name} ${_kind} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7} ${CMAKE_MATCH_8}")
      if(_claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} ${_kind} ([^\n]+)")
        list(APPEND _spread_rows "${_row} ${CMAKE_MATCH_1}")
      else()
        list(APPEND _spread_rows "${_row} unclaimed")
      endif()
    elseif(_function_name MATCHES "^(canonicalString(Released|Saved|Lookalike|Loaded)|decimalBigInt(Released|Saved|Second|Loaded|Negative))$" AND _line MATCHES "^site ")
      if(_function_name MATCHES "^decimalBigInt")
        set(_index_family decimal_bigint)
      else()
        set(_index_family canonical_string)
      endif()
      if(NOT _line MATCHES "^site ([0-9]+) kind (obj|arr) made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected literal index observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_kind "${CMAKE_MATCH_2}")
      set(_row "${_function_name} ${_kind} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7} ${CMAKE_MATCH_8}")
      list(APPEND _${_index_family}_literal_pcs "${_function_name} ${_kind} ${_pc}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} ${_kind} ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed ${_kind} at pc ${_pc}")
      endif()
      list(APPEND _${_index_family}_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^arrayFrame(Private|Returned|SavedRead|Overwrite|LoadedAlias|Published|Call|Cycle|TransientCycle)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind (obj|arr) made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected array-frame observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_kind "${CMAKE_MATCH_2}")
      set(_row "${_function_name} ${_kind} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7} ${CMAKE_MATCH_8}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} ${_kind} ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed ${_kind} at pc ${_pc}")
      endif()
      list(APPEND _array_frame_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameDeleted(Child|SavedRead|TransientCycle)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected object deletion observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_deletion_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameCopied(Child|Overwrite|SavedRead)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected object copy observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_copy_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameCopied(ConditionalAlias|ConditionalSource|SwitchSaved|LiteralOverwrite)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected object copy path observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_copy_path_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name STREQUAL "objectFrameSwitchReleased" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected source switch selector observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_switch_selector_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name STREQUAL "objectFrameNegatedReleased" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected logical negation observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_negation_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrame(Typeof|Void)Released$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected total unary observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_total_unary_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameStaticBinary(Released|Opaque|BigInt)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected static binary observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_static_binary_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameArithmeticUnary(Released|Saved|Opaque|BigInt)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected arithmetic unary observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_arithmetic_unary_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameLooseEquality(Released|Saved|Opaque|BigInt|Relational|Literal)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected loose equality observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_loose_equality_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameRelational(Saved|Unordered|Opaque|BigInt|Retained)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected relational observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_relational_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameArithmeticBinary(Saved|Numbers|Opaque|BigInt|Retained)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected arithmetic binary observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_arithmetic_binary_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameAddConcat(Saved|Numbers|Template|OpaqueAdd|OpaqueTemplate|BigInt|Retained)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected Add/Concat observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_add_concat_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^primitive(UShr|MixedStatic|MixedAdd)(Early|Retained|Opaque)$" AND _line MATCHES "^alloc ")
      string(REGEX MATCH "(UShr|MixedStatic|MixedAdd)(Early|Retained|Opaque)$" _static_name "${_function_name}")
      string(TOLOWER "${CMAKE_MATCH_1}" _static_family)
      if(NOT _line MATCHES "^alloc ([0-9]+) kind (obj|arr)$")
        message(FATAL_ERROR "${_function_name}: unexpected BigInt source allocation: ${_line}")
      endif()
      list(APPEND _primitive_${_static_family}_literal_pcs "${_function_name} ${CMAKE_MATCH_1} ${CMAKE_MATCH_2}")
    elseif(_function_name MATCHES "^primitive(UShr|MixedStatic|MixedAdd)(Early|Retained|Opaque)$" AND _line MATCHES "^site ")
      string(REGEX MATCH "(UShr|MixedStatic|MixedAdd)(Early|Retained|Opaque)$" _static_name "${_function_name}")
      string(TOLOWER "${CMAKE_MATCH_1}" _static_family)
      set(_static_suffix "${CMAKE_MATCH_2}")
      set(_static_error_pc "${_primitive_${_static_family}_error_pc_${_static_suffix}}")
      if(NOT _line MATCHES "^site ([0-9]+) kind (obj|arr) made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected BigInt observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_kind "${CMAKE_MATCH_2}")
      set(_row "${_function_name} ${_kind} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7} ${CMAKE_MATCH_8}")
      if(_pc STREQUAL _static_error_pc)
        if(NOT _line STREQUAL "site ${_static_error_pc} kind obj made 1 confined 0 escaped 1 unresolved 0 unchecked 0 routes thrown:1")
          message(FATAL_ERROR "${_function_name}: the independent BigInt Error was not retained through unwinding: ${_line}")
        endif()
        if(_claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_static_error_pc} [^\n]+")
          message(FATAL_ERROR "${_function_name}: the implicit BigInt Error acquired a source allocation claim")
        endif()
        list(APPEND _primitive_${_static_family}_error_rows "${_row} pc${_pc} unclaimed")
      else()
        string(REGEX MATCHALL "escape ${_program_hash} ${_function_index} ${_pc} ${_kind} [^\n]+" _static_claims "${_claim_text}")
        list(LENGTH _static_claims _static_claim_count)
        if(NOT _static_claim_count EQUAL 1)
          message(FATAL_ERROR "${_function_name}: missing or duplicate BigInt claim at pc ${_pc}")
        endif()
        if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} ${_kind} ([^\n]+)")
          message(FATAL_ERROR "${_function_name}: no compiler claim for observed ${_kind} at pc ${_pc}")
        endif()
        list(APPEND _primitive_${_static_family}_rows "${_row} ${CMAKE_MATCH_1} pc${_pc}")
      endif()
    elseif(_function_name MATCHES "^primitivePlus(Early|Retained|Opaque)$" AND _line MATCHES "^alloc ")
      if(NOT _line MATCHES "^alloc ([0-9]+) kind obj$")
        message(FATAL_ERROR "${_function_name}: unexpected BigInt Plus source allocation: ${_line}")
      endif()
      list(APPEND _primitive_plus_literal_pcs "${_function_name} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^primitivePlus(Early|Retained|Opaque)$" AND _line MATCHES "^site ")
      string(REGEX REPLACE "^primitivePlus" "" _plus_suffix "${_function_name}")
      set(_plus_error_pc "${_primitive_plus_error_pc_${_plus_suffix}}")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected BigInt Plus observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(_pc STREQUAL _plus_error_pc)
        if(NOT _line STREQUAL "site ${_plus_error_pc} kind obj made 1 confined 0 escaped 1 unresolved 0 unchecked 0 routes thrown:1")
          message(FATAL_ERROR "${_function_name}: the independent Plus Error was not retained through unwinding: ${_line}")
        endif()
        if(_claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_plus_error_pc} [^\n]+")
          message(FATAL_ERROR "${_function_name}: the implicit Plus Error acquired a source allocation claim")
        endif()
        list(APPEND _primitive_plus_error_rows "${_row} pc${_pc} unclaimed")
      else()
        string(REGEX MATCHALL "escape ${_program_hash} ${_function_index} ${_pc} obj [^\n]+" _plus_claims "${_claim_text}")
        list(LENGTH _plus_claims _plus_claim_count)
        if(NOT _plus_claim_count EQUAL 1)
          message(FATAL_ERROR "${_function_name}: missing or duplicate BigInt Plus claim at pc ${_pc}")
        endif()
        if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
          message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
        endif()
        list(APPEND _primitive_plus_rows "${_row} ${CMAKE_MATCH_1} pc${_pc}")
      endif()
    elseif(_function_name MATCHES "^primitiveMixedSub(Early|Retained|Opaque)$" AND _line MATCHES "^alloc ")
      if(NOT _line MATCHES "^alloc ([0-9]+) kind obj$")
        message(FATAL_ERROR "${_function_name}: unexpected mixed BigInt Sub source allocation: ${_line}")
      endif()
      list(APPEND _primitive_mixed_sub_literal_pcs "${_function_name} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^primitiveMixedSub(Early|Retained|Opaque)$" AND _line MATCHES "^site ")
      string(REGEX REPLACE "^primitiveMixedSub" "" _mixed_sub_suffix "${_function_name}")
      set(_mixed_sub_error_pc "${_primitive_mixed_sub_error_pc_${_mixed_sub_suffix}}")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected mixed BigInt Sub observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(_pc STREQUAL _mixed_sub_error_pc)
        if(NOT _line STREQUAL "site ${_mixed_sub_error_pc} kind obj made 1 confined 0 escaped 1 unresolved 0 unchecked 0 routes thrown:1")
          message(FATAL_ERROR "${_function_name}: the independent mixed Sub Error was not retained through unwinding: ${_line}")
        endif()
        if(_claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_mixed_sub_error_pc} [^\n]+")
          message(FATAL_ERROR "${_function_name}: the implicit mixed Sub Error acquired a source allocation claim")
        endif()
        list(APPEND _primitive_mixed_sub_error_rows "${_row} pc${_pc} unclaimed")
      else()
        string(REGEX MATCHALL "escape ${_program_hash} ${_function_index} ${_pc} obj [^\n]+" _mixed_sub_claims "${_claim_text}")
        list(LENGTH _mixed_sub_claims _mixed_sub_claim_count)
        if(NOT _mixed_sub_claim_count EQUAL 1)
          message(FATAL_ERROR "${_function_name}: missing or duplicate mixed BigInt Sub claim at pc ${_pc}")
        endif()
        if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
          message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
        endif()
        list(APPEND _primitive_mixed_sub_rows "${_row} ${CMAKE_MATCH_1} pc${_pc}")
      endif()
    elseif(_function_name MATCHES "^primitiveMixed(Mul|Div|Mod)(Early|Retained|Opaque)$" AND _line MATCHES "^alloc ")
      string(REGEX REPLACE "^primitiveMixed(Mul|Div|Mod).*$" "\\1" _mixed_kind "${_function_name}")
      string(TOLOWER "${_mixed_kind}" _mixed_operation)
      if(NOT _line MATCHES "^alloc ([0-9]+) kind obj$")
        message(FATAL_ERROR "${_function_name}: unexpected mixed BigInt ${_mixed_kind} source allocation: ${_line}")
      endif()
      list(APPEND _primitive_mixed_${_mixed_operation}_literal_pcs "${_function_name} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^primitiveMixed(Mul|Div|Mod)(Early|Retained|Opaque)$" AND _line MATCHES "^site ")
      string(REGEX REPLACE "^primitiveMixed(Mul|Div|Mod).*$" "\\1" _mixed_kind "${_function_name}")
      string(TOLOWER "${_mixed_kind}" _mixed_operation)
      string(REGEX REPLACE "^primitiveMixed${_mixed_kind}" "" _mixed_suffix "${_function_name}")
      set(_mixed_error_pc "${_primitive_mixed_${_mixed_operation}_error_pc_${_mixed_suffix}}")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected mixed BigInt ${_mixed_kind} observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(_pc STREQUAL _mixed_error_pc)
        if(NOT _line STREQUAL "site ${_mixed_error_pc} kind obj made 1 confined 0 escaped 1 unresolved 0 unchecked 0 routes thrown:1")
          message(FATAL_ERROR "${_function_name}: the independent mixed ${_mixed_kind} Error was not retained through unwinding: ${_line}")
        endif()
        if(_claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_mixed_error_pc} [^\n]+")
          message(FATAL_ERROR "${_function_name}: the implicit mixed ${_mixed_kind} Error acquired a source allocation claim")
        endif()
        list(APPEND _primitive_mixed_${_mixed_operation}_error_rows "${_row} pc${_pc} unclaimed")
      else()
        string(REGEX MATCHALL "escape ${_program_hash} ${_function_index} ${_pc} obj [^\n]+" _mixed_claims "${_claim_text}")
        list(LENGTH _mixed_claims _mixed_claim_count)
        if(NOT _mixed_claim_count EQUAL 1)
          message(FATAL_ERROR "${_function_name}: missing or duplicate mixed BigInt ${_mixed_kind} claim at pc ${_pc}")
        endif()
        if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
          message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
        endif()
        list(APPEND _primitive_mixed_${_mixed_operation}_rows "${_row} ${CMAKE_MATCH_1} pc${_pc}")
      endif()
    elseif(_function_name MATCHES "^objectFrameBigIntMixed(Saved|Primitives|Paths|Numbers|Opaque|Object|Retained|Strings)$" AND _line MATCHES "^alloc ")
      if(NOT _line MATCHES "^alloc ([0-9]+) kind obj$")
        message(FATAL_ERROR "${_function_name}: unexpected mixed BigInt comparison source allocation: ${_line}")
      endif()
      list(APPEND _object_mixed_bigint_literal_pcs "${_function_name} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameBigIntMixed(Saved|Primitives|Paths|Numbers|Opaque|Object|Retained|Strings)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected mixed BigInt comparison observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      string(REGEX MATCHALL "escape ${_program_hash} ${_function_index} ${_pc} obj [^\n]+" _mixed_bigint_claims "${_claim_text}")
      list(LENGTH _mixed_bigint_claims _mixed_bigint_claim_count)
      if(NOT _mixed_bigint_claim_count EQUAL 1)
        message(FATAL_ERROR "${_function_name}: missing or duplicate mixed BigInt comparison claim at pc ${_pc}")
      endif()
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_mixed_bigint_rows "${_row} ${CMAKE_MATCH_1} pc${_pc}")
    elseif(_function_name MATCHES "^objectFrameStringBigInt(Saved|Paths|Template|OpaqueAdd|OpaqueTemplate|Object|Mixed|Retained)$" AND _line MATCHES "^alloc ")
      if(NOT _line MATCHES "^alloc ([0-9]+) kind obj$")
        message(FATAL_ERROR "${_function_name}: unexpected String BigInt source allocation: ${_line}")
      endif()
      list(APPEND _object_string_bigint_literal_pcs "${_function_name} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameStringBigInt(Saved|Paths|Template|OpaqueAdd|OpaqueTemplate|Object|Mixed|Retained)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected String BigInt observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      string(REGEX MATCHALL "escape ${_program_hash} ${_function_index} ${_pc} obj [^\n]+" _string_bigint_claims "${_claim_text}")
      list(LENGTH _string_bigint_claims _string_bigint_claim_count)
      if(NOT _string_bigint_claim_count EQUAL 1)
        message(FATAL_ERROR "${_function_name}: missing or duplicate String BigInt claim at pc ${_pc}")
      endif()
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_string_bigint_rows "${_row} ${CMAKE_MATCH_1} pc${_pc}")
    elseif(_function_name MATCHES "^objectFrameBigIntEquality(Saved|Opaque|Mixed|Retained)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected BigInt equality observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_bigint_equality_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameBigIntRelational(Saved|Opaque|Mixed|Computed|Retained)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected BigInt relational observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_bigint_relational_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameBigIntUnary(Saved|Paths|Opaque|Mixed|Retained)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected BigInt unary observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_bigint_unary_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameBigIntBinary(Saved|Paths|Opaque|Mixed|Retained)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected BigInt binary observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_bigint_binary_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameBigIntStatic(Saved|Paths|Opaque|Mixed|Shift|Retained)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected BigInt observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
        message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
      endif()
      list(APPEND _object_bigint_static_rows "${_row} ${CMAKE_MATCH_1}")
    elseif(_function_name STREQUAL "objectFrameBigIntShiftEarly" AND _line MATCHES "^alloc ")
      if(NOT _line MATCHES "^alloc ([0-9]+) kind obj$")
        message(FATAL_ERROR "unexpected signed-shift literal allocation: ${_line}")
      endif()
      list(APPEND _object_bigint_shift_literal_pcs "${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameBigIntShift(Saved|Paths|Opaque|Mixed|Early|Retained)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected signed BigInt shift observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(_function_name STREQUAL "objectFrameBigIntShiftEarly" AND _pc STREQUAL "25")
        if(NOT _line STREQUAL "site 25 kind obj made 1 confined 0 escaped 1 unresolved 0 unchecked 0 routes thrown:1")
          message(FATAL_ERROR "the signed shift's independent Error was not retained through unwinding: ${_line}")
        endif()
        if(_claim_text MATCHES "escape ${_program_hash} ${_function_index} 25 [^\n]+")
          message(FATAL_ERROR "the implicit signed-shift Error acquired a source allocation claim")
        endif()
        list(APPEND _object_bigint_shift_error_rows "${_row} pc25 unclaimed")
      else()
        if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
          message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
        endif()
        list(APPEND _object_bigint_shift_rows "${_row} ${CMAKE_MATCH_1}")
      endif()
    elseif(_function_name MATCHES "^objectFrameBigIntDivMod(Div|Mod)Early$" AND _line MATCHES "^alloc ")
      if(NOT _line MATCHES "^alloc ([0-9]+) kind obj$")
        message(FATAL_ERROR "${_function_name}: unexpected BigInt Div/Mod literal allocation: ${_line}")
      endif()
      list(APPEND _object_bigint_divmod_literal_pcs "${_function_name} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameBigIntDivMod(Saved|Paths|Opaque|Mixed|DivEarly|ModEarly|Retained)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected BigInt Div/Mod observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      if(_function_name MATCHES "^objectFrameBigIntDivMod(Div|Mod)Early$" AND _pc STREQUAL "25")
        if(NOT _line STREQUAL "site 25 kind obj made 1 confined 0 escaped 1 unresolved 0 unchecked 0 routes thrown:1")
          message(FATAL_ERROR "${_function_name}: the independent Error was not retained through unwinding: ${_line}")
        endif()
        if(_claim_text MATCHES "escape ${_program_hash} ${_function_index} 25 [^\n]+")
          message(FATAL_ERROR "${_function_name}: the implicit BigInt Div/Mod Error acquired a source allocation claim")
        endif()
        list(APPEND _object_bigint_divmod_error_rows "${_row} pc25 unclaimed")
      else()
        if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
          message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
        endif()
        list(APPEND _object_bigint_divmod_rows "${_row} ${CMAKE_MATCH_1}")
      endif()
    elseif(_function_name MATCHES "^objectFrameBigIntPow(Negative|Cap)Early$" AND _line MATCHES "^alloc ")
      if(NOT _line MATCHES "^alloc ([0-9]+) kind obj$")
        message(FATAL_ERROR "${_function_name}: unexpected BigInt Pow literal allocation: ${_line}")
      endif()
      list(APPEND _object_bigint_pow_literal_pcs "${_function_name} ${CMAKE_MATCH_1}")
    elseif(_function_name MATCHES "^objectFrameBigIntPow(Saved|Paths|Opaque|Mixed|NegativeEarly|CapEarly|Retained)$" AND _line MATCHES "^site ")
      if(NOT _line MATCHES "^site ([0-9]+) kind obj made ([0-9]+) confined ([0-9]+) escaped ([0-9]+) unresolved ([0-9]+) unchecked ([0-9]+) routes ([^ ]+)$")
        message(FATAL_ERROR "${_function_name}: unexpected BigInt Pow observation: ${_line}")
      endif()
      set(_pc "${CMAKE_MATCH_1}")
      set(_row "${_function_name} ${CMAKE_MATCH_2} ${CMAKE_MATCH_3} ${CMAKE_MATCH_4} ${CMAKE_MATCH_5} ${CMAKE_MATCH_6} ${CMAKE_MATCH_7}")
      set(_pow_error_pc "")
      if(_function_name MATCHES "^objectFrameBigIntPow(Negative|Cap)Early$")
        set(_pow_error_pc "${_pow_error_pc_${CMAKE_MATCH_1}}")
      endif()
      if(_pc STREQUAL _pow_error_pc)
        if(NOT _line STREQUAL "site ${_pow_error_pc} kind obj made 2 confined 0 escaped 2 unresolved 0 unchecked 0 routes thrown:2")
          message(FATAL_ERROR "${_function_name}: the independent Errors were not retained through unwinding: ${_line}")
        endif()
        if(_claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pow_error_pc} [^\n]+")
          message(FATAL_ERROR "${_function_name}: the implicit BigInt Pow Error acquired a source allocation claim")
        endif()
        list(APPEND _object_bigint_pow_error_rows "${_row} pc${_pow_error_pc} unclaimed")
      else()
        if(NOT _claim_text MATCHES "escape ${_program_hash} ${_function_index} ${_pc} obj ([^\n]+)")
          message(FATAL_ERROR "${_function_name}: no compiler claim for observed object at pc ${_pc}")
        endif()
        list(APPEND _object_bigint_pow_rows "${_row} ${CMAKE_MATCH_1}")
      endif()
    endif()
  endforeach()
