#!/usr/bin/env python3
"""Compile the compositor's GLSL to SPIR-V and emit it as a committed header.

The SPIR-V is generated ONCE and checked in, the same way font8x8.hpp and
cthtml's entities.hpp are. A build-time shader compilation step would put glslc
on the critical path of every build and every CI runner, for shaders that change
about never.

    python3 tools/gen-shaders.py        # regenerate include/ctbrowser/gpu/shaders/tile_spv.hpp

Needs glslc (shaderc). SPIR-V means the Vulkan driver; DXIL and MSL need their
own compilers and belong with the Windows and macOS platform work.
"""
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent.parent
# the GLSL sources and the header generated from them live together, under
# include/ with the rest of the engine
SHADERS = HERE / "include" / "ctbrowser" / "gpu" / "shaders"
GENERATED = SHADERS


def compile_one(name: str, stage: str) -> bytes:
    source = SHADERS / f"{name}.glsl"
    out = subprocess.run(
        ["glslc", f"-fshader-stage={stage}", str(source), "-o", "-"],
        check=True, capture_output=True,
    )
    return out.stdout


def as_array(name: str, data: bytes) -> str:
    body = ",".join(str(b) for b in data)
    wrapped = []
    while body:
        cut = body.rfind(",", 0, 92)
        if cut == -1 or len(body) < 92:
            wrapped.append(body)
            break
        wrapped.append(body[:cut + 1])
        body = body[cut + 1:]
    lines = "\n    ".join(wrapped)
    return (f"inline constexpr unsigned char {name}[] = {{\n    {lines}}};\n"
            f"inline constexpr unsigned long {name}_size = sizeof({name});\n")


def main() -> int:
    try:
        vert = compile_one("tile.vert", "vertex")
        frag = compile_one("tile.frag", "fragment")
    except FileNotFoundError:
        print("glslc not found; install shaderc to regenerate", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as e:
        sys.stderr.write(e.stderr.decode())
        return 1

    header = GENERATED / "tile_spv.hpp"
    header.write_text(
        "#ifndef CTBROWSER_V2_GPU_TILE_SPV_HPP\n"
        "#define CTBROWSER_V2_GPU_TILE_SPV_HPP\n\n"
        "// GENERATED by tools/gen-shaders.py from tile.vert.glsl / tile.frag.glsl.\n"
        "// Do not edit; edit the GLSL and regenerate.\n\n"
        "namespace ctbrowser::gpu::shaders {\n\n"
        + as_array("tile_vert_spv", vert) + "\n"
        + as_array("tile_frag_spv", frag) +
        "\n} // namespace ctbrowser::gpu::shaders\n\n"
        "#endif\n"
    )
    print(f"wrote {header} ({len(vert)} + {len(frag)} bytes of SPIR-V)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
